version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    entrypoint: .docker/entrypoint.sh
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: "my-database"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 
      
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "16543:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    depends_on:
      - postgres
    networks:
      - postgres
    volumes:
       - ./pgadmin:/root/.pgadmin

networks:
  postgres:
    driver: bridge
